# [REMINDER] We advise that you use command blocks to disable end crystals instead of this plugin.
# [REMINDER] (People can't remove the end crystal)
# [REMINDER] Repeating always active command block: "kill @e[type=end_crystal]"
disallow-end-crystals: true

# Timer of the placing and breaking in seconds. (They share a different timer!)
timers:
  place: 30
  break: 30
