# [REMINDER] We advise that you use command blocks to disable end crystals instead of this plugin.
# [REMINDER] (People can't remove the end crystal)
# [REMINDER] Repeating always active command block: "kill @e[type=end_crystal]"
disallow-end-crystals: true

# Timer of the placing, breaking and interacting in seconds. (They use a different timer!)
timers:
  place: 60
  break: 60
  interact: 60

teleport:
  pc:
    # The y-level the player is teleported if they are below y=0
    below-0: 10

display:
  # Shows the bossbars of placing and breaking (for timers)
  show-bossbar: true
  # Sends the current timer in chat if player places or breaks a block...
  send-timer-in-chat:
    # ...when player can place/break a block (not affected by timer-disapproved)
    timer-approved: false
    # ...when player can't place/break a block (not affected by timer-approved)
    timer-disapproved: false
  # If your server is going to be big, enabling this might lag the players.
  show-other-players: false

# Messages that are broadcasted to the players
messages:
  commands:
    # might want to troll them here
    break-only-mode: "The place is resumed!"
    resume-mode: "The place is resumed!"
    pause-mode: "Please wait; the place is paused. (Most likely for backing up the world)"
    reload-config: "The config file of the place is reloaded. If there exists any bugs, please do not hesitate to report to r/placemc"
    pc:
      not-yet: "Successfully set gamemode to: CREATIVE"
      already: "You are already in creative mode!"
      below-0: "You can't go below y=0!"
    ps:
      not-yet: "Successfully set gamemode to: SPECTATOR"
      already: "You are already in spectator mode!"
  timers:
    place: "You have %placeTimer% second(s) left!"
    break: "You have %breakTimer% second(s) left!"
    interact: "You have %interactTimer% second(s) left!"
  breaking-restricted-blocks: "You can't escape."
  placing-restricted-blocks: "To prevent griefing and potentially breaking the map, we disabled that block."
  dropping-items: "To prevent lag from dropped items, we have disabled dropped items."
  # What to send when player places a block during break only mode
  placing-in-bom: ""