name: place
version: '1.2'
main: com.github.ninathedev.place.Place
api-version: '1.16'
description: 'This plugin recreates r/place, but the canvas is 3D'
load: POSTWORLD
author: ninathedev
website: github.com/ninathedev/placemc
commands:
  reloadconfig:
    description: Reloads the config.yml file.
    usage: /<command>
    permission: place.reloadconf
  breakonlymode:
    description: Players will no longer place blocks
    usage: /<command>
    permission: place.modes
  pausemode:
    description: Players will no longer place or break blocks
    usage: /<command>
    permission: place.modes
  resumemode:
    description: Players will continue with the place
    usage: /<command>
    permission: place.modes
  pc:
    description: Changes your gamemode to creative.
    usage: /<command>
    permission: place.gamemodes
  ps:
    description: Changes your gamemode to spectator.
    usage: /<command>
    permission: place.gamemodes
permissions:
  place.reloadconf:
    description: "Allows you to reload the configuration file"
    default: op
  place.modes:
    description: "MODES!!! :):)"
    default: op
  place.bypassTimer:
    description: "Bypasses the timer"
    default: op
  place.bypassBlockLimiter:
    description: "Used when you want to place command blocks or remove bedrock and stuff"
    default: op
  place.gamemodes:
    description: "Lets players switch gamemodes thru /pc and /ps"
    default: not op